export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  SYSTEM_OWNER: 'SYSTEM_OWNER',
  PLANT_OPERATOR: 'PLANT_OPERATOR',
  ENERGY_TRADER: 'ENERGY_TRADER',
  UTILITY_PROVIDER: 'UTILITY_PROVIDER',
  INSTALLER: 'INSTALLER',
  ENGINEER: 'ENGINEER',
  MAINTENANCE_ENGINEER: 'MAINTENANCE_ENGINEER',
  CONSUMER: 'CONSUMER',
  CUSTOMER: 'CUSTOMER',
} as const;

export const ALL_ROLES = Object.values(ROLES);

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ROLES.ADMIN];

export const PRIVILEGED_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.SYSTEM_OWNER,
  ROLES.PLANT_OPERATOR,
];
